on: push
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@main
      env:
        PAGES_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
